#!/bin/bash

nopanel_module_php-fpm_info() {
    nplib_require $NOPANEL_LIB/module.inc
    nplib_require $NOPANEL_LIB/php.inc

    nplib_command_echo "noPanel PHP (FPM) module information"

    nplib_command_echo "Supported PHP versions   : $PHP_SUPPORTED_VERSIONS"
    nplib_command_echo "Default PHP version      : $PHP_DEFAULT_VERSION"

    [ "$param_output" = 'json' ] && local extra="{supportedVersion: \"$PHP_SUPPORTED_VERSIONS\", defaultVersion: \"$PHP_DEFAULT_VERSION\"}"

    nplib_command_output 'ok' 'PHP (FPM) module information' "$extra"
}

# If this files is _not_ being sourced, act immediately
if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    npctl $@
fi