#!/bin/bash

nopanel_module_php-fpm_install() {
    nplib_auto_elevate
    nplib_require $NOPANEL_LIB/module.inc
    nplib_command_echo "Installing noPanel PHP (FPM) module"

    osal_package_preinstall > /dev/null 2>&1

    case $OS_TYPE in
        'fedora')
            nplib_command_echo " - Adding Remi repository"
            osal_package_install "https://rpms.remirepo.net/fedora/remi-release-${OS_VERSION}.rpm" > /dev/null 2>&1
            ;;
        'rhel')
            nplib_command_echo " - Adding Remi repository"
            osal_package_install "https://rpms.remirepo.net/enterprise/remi-release-${OS_VERSION}.rpm" > /dev/null 2>&1
            ;;
    esac

    nplib_modules_set_installed 'php-fpm' 'true'

    nopanel module php-fpm add --version default
    
    nplib_command_output 'ok' 'PHP (FPM) module installed'
}
