#!/bin/bash

nopanel_module_list() {
    nplib_require $NOPANEL_LIB/module.inc
     
    if [ "$param_output" = 'json' ]; then
        extra=$(nplib_modules_list_json)
    else
        extra=$(nplib_modules_list)
    fi

    nplib_command_output 'ok' 'noPanel module information' "$extra"
}

# If this files is _not_ being sourced, act immediately
if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    npctl $@
fi