#!/bin/bash

if [[ -z "$NOPANEL_VERSION" ]]; then
    echo "This file should not be called without the proper environment. Use nopanel CLI instead."
    exit 1
fi

nopanel_commit() {
    nplib_auto_elevate
    nplib_command_echo "= Applying changes"

    MODS='user database web'
    for MOD in $MODS; do
        nopanel $MOD commit
    done

    nplib_command_output 'ok' 'Changes applied'
}

# If this files is _not_ being sourced, act immediately
if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    npctl $@
fi