#!/bin/bash

if [[ -z "$NOPANEL_VERSION" ]]; then
    echo "This file should not be called without the proper environment. Use nopanel CLI instead."
    exit 1
fi

nopanel_upgrade() {
    nplib_auto_elevate
    nplib_command_echo "Upgrading noPanel to version $NOPANEL_VERSION"

    # get getssl to manage Let's Encrypt certificates
    curl --silent https://raw.githubusercontent.com/srvrco/getssl/master/getssl > $NOPANEL_LIB/getssl
    chmod a+x $NOPANEL_LIB/getssl

    mkdir -p $NOPANEL_ETC/pki
    mkdir -p /var/www/html/.well-known/acme-challenge

    # update version
    osal_json_set "/etc/nopanel/nopanel.json" ".version=\"$NOPANEL_VERSION\""

    nplib_command_output 'ok' 'noPanel ready'
}

# If this files is _not_ being sourced, act immediately
if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    npctl $@
fi