#!/bin/bash

if [[ -z "$NOPANEL_VERSION" ]]; then
    echo "This file should not be called without the proper environment. Use nopanel CLI instead."
    exit 1
fi

nopanel_upgrade() {
    nplib_auto_elevate
    nplib_command_echo "Upgrading noPanel to version $NOPANEL_VERSION"

    osal_json_set "/etc/nopanel/nopanel.json" ".version=\"$NOPANEL_VERSION\""

    nplib_command_output 'ok' 'noPanel ready'
}

# If this files is _not_ being sourced, act immediately
if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    npctl $@
fi