#!/bin/bash

nopanel_web_domain_add() {
    if [[ "$param_help" ]]; then
        nopanel web help
        return
    fi

    if [[ ! "$param_user" ]]; then
        nopanel_command_return 'error' 'Username not specified (--user)'
        return
    fi
    if [[ ! "$param_domain" ]]; then
        nopanel_command_return 'error' 'Domain name not specified'
        return
    fi

    # Update noPanel DB
    nopanel_command_echo "Adding domain $param_domain for user $param_user..."

    local domain_exists=$(osal_json_get "$NOPANEL_ETC/domains.json" ".domains[] | select(.name == \"$param_domain\") | .name")
    [[ "$domain_exists" ]] || osal_json_set "$NOPANEL_ETC/domains.json" ".domains += [{name: \"$param_domain\"}]"
    osal_json_set "$NOPANEL_ETC/domains.json" ".domains |= map((select(.name == \"$param_domain\") | .user = \"$param_user\" | .aliases = \"$param_aliases\") // .)"

    # Build configuration for domain
    nopanel web domain rebuild

    # Resload web server config
    nopanel module apache reload

    nopanel_command_return 'ok' 'Domain added'
}
