#!/bin/bash

nopanel_web_domain_add() {
    if [[ "$param_help" ]]; then
        nopanel web help
        return
    fi

    if [[ ! "$param_user" ]]; then
        nplib_command_output 'error' 'Username not specified (--user)'
        return
    fi
    if [[ ! "$param_domain" ]]; then
        nplib_command_output 'error' 'Domain name not specified'
        return
    fi

    nplib_require $NOPANEL_LIB/domain.inc

    # Default values
    [[ ! "$param_php" ]] && param_php='no'

    # Update noPanel DB
    nplib_command_echo "Adding domain $param_domain for user $param_user..."

    nplib_domains_set "$param_domain" 'name' "$param_domain"
    nplib_domains_set "$param_domain" 'user' "$param_user"

    # Call mod (-> commit (-> reload))
    if nopanel web domain mod; then
        nplib_command_output 'ok' 'Web domain created'
    fi
}
