#!/bin/bash

nopanel_web_domain_list() {
    if [[ "$param_help" ]]; then
        nopanel web help
        return
    fi

    if [[ ! "$param_user" ]]; then
        nopanel_command_return 'error' 'Username not specified (--user)'
        return
    fi

    source $NOPANEL_LIB/domain.inc

    if [[ "$param_output_json" ]]; then
        #local domainlist=
        nopanel_command_return 'ok' 'Domain list' $(nplib_domains_list_json "$param_user")
    else
        local domainlist=$(nplib_domains_list "$param_user")
        nopanel_command_return 'ok' 'Domain list' "$domainlist"
    fi

}
