#!/bin/bash

nopanel_web_domain_mod() {
    nplib_command_echo "= Set web domain"
    
    if [[ "$param_help" ]]; then
        nopanel web help
        return
    fi
    
    if [[ ! "$param_user" ]]; then
        nplib_command_output 'error' 'Username not specified (--user)'
        return
    fi
    if [[ ! "$param_domain" ]]; then
        nplib_command_output 'error' 'Domain name not specified (--domain)'
        return
    fi
    if [[ "$param_ssl" ]]; then
        case "$param_ssl" in
            'le'|'self'|'no')
                : # ok
            ;;
            *)
                nplib_command_output 'error' "Invalid value for --ssl (must be 'le', 'self' or 'no')"
                return 1
            ;;
        esac
    fi
    
    nplib_require $NOPANEL_LIB/validation.inc
    nplib_require $NOPANEL_LIB/domain.inc
    
    if ! nplib_domains_exists "$param_domain"; then
        nplib_command_output 'error' 'Domain does not exist'
        return
    fi
    
    # Validate aliases if being set
    if [[ "$param_aliases" ]]; then
        if ! nplib_validate_aliases "$param_aliases"; then
            return 1
        fi
    fi
    
    # Update noPanel DB
    nplib_domains_set "$param_domain" 'web' 'true'
    [[ "$param_aliases" ]] && nplib_domains_set "$param_domain" 'web_aliases' "$param_aliases"
    [[ "$param_ssl" ]] && nplib_domains_set "$param_domain" 'web_ssl' "$param_ssl"
    
    if nplib_is_false $param_php; then
        nplib_domains_set "$param_domain" 'web_php' 'false'
        elif [[ $param_php ]]; then
        nplib_domains_set "$param_domain" 'web_php' "$param_php"
    fi
    
    if [[ "$param_commit" ]]; then
        nopanel web domain commit
    fi
    
    nplib_command_output 'ok' 'Web domain saved'
}
