#!/bin/bash

nopanel_web_domain_remove() {
    if [[ "$param_help" ]]; then
        nopanel web help
        return
    fi

    if [[ ! "$param_user" ]]; then
        nplib_command_output 'error' 'Username not specified (--user)'
        return
    fi
    if [[ ! "$param_domain" ]]; then
        nplib_command_output 'error' 'Domain name not specified (--domain)'
        return
    fi

    nplib_require $NOPANEL_LIB/domain.inc

    if ! nplib_domains_exists "$param_domain"; then
        nplib_command_output 'error' 'Domain does not exist'
        return
    fi

    # Update noPanel DB
    nplib_command_echo "Deleting $param_domain..."

    nplib_domains_set "$param_domain" 'web' 'delete'

    nplib_command_output 'ok' 'Web domain deleted'

    if [[ "$param_commit" ]]; then
        nopanel web domain commit
    fi
}
