#!/bin/bash

nopanel_module_apache_install() {
    nplib_elevate
    nplib_require $NOPANEL_LIB/module.inc

    nplib_command_echo "Installing noPanel Apache module..."

    osal_service_stop $OSAL_SERVICE_APACHE > /dev/null 2>&1
    nplib_config_backup 'apache-install' $OSAL_PATH_APACHE_CONF $OSAL_PATH_APACHE_CONF_D

    nplib_command_echo " - Installing Apache package(s)"
    osal_package_preinstall > /dev/null 2>&1
    osal_package_install $OSAL_PKG_APACHE $OSAL_PKG_APACHE_EXTRA > /dev/null 2>&1

    nplib_command_echo " - Creating configuration files and directories"
    mkdir -p $OSAL_PATH_APACHE_CONF_D/domains
    mkdir -p /var/log/$OSAL_PKG_APACHE/domains
    chmod 0770 /var/log/$OSAL_PKG_APACHE
    chown root:nopanel-admins /var/log/$OSAL_PKG_APACHE
    touch /var/log/$OSAL_PKG_APACHE/access.log /var/log/$OSAL_PKG_APACHE/error.log
    chmod 660 /var/log/$OSAL_PKG_APACHE/access.log /var/log/$OSAL_PKG_APACHE/error.log
    chown root:nopanel-admins /var/log/$OSAL_PKG_APACHE/access.log /var/log/$OSAL_PKG_APACHE/error.log
    chmod 751 /var/log/$OSAL_PKG_APACHE/domains

    # Enable/disable required modules
    osal_apache_module_enable rewrite > /dev/null 2>&1
    osal_apache_module_enable suexec > /dev/null 2>&1
    osal_apache_module_enable ssl > /dev/null 2>&1
    osal_apache_module_enable actions > /dev/null 2>&1

    cp -f $NOPANEL_DATA/$OS_BASE/apache/${OSAL_PKG_APACHE}.conf $OSAL_PATH_APACHE_CONF/
    cp -f $NOPANEL_DATA/$OS_BASE/apache/status.conf $OSAL_PATH_APACHE_CONF_D/
    cp -f $NOPANEL_DATA/$OS_BASE/logrotate/${OSAL_PKG_APACHE} $OSAL_PATH_LOGROTATE_CONF_D/

    if [ "$OS_BASE" = 'rhel' ]; then
        echo "# Disabled by noPanel" > $OSAL_PATH_APACHE_CONF_D/ssl.conf
        echo "# Disabled by noPanel" > $OSAL_PATH_APACHE_CONF_D/welcome.conf
        echo "# Disabled by noPanel" > $OSAL_PATH_APACHE_CONF_D/userdir.conf
    elif [ "$OS_BASE" = 'debian' ]; then
        echo "# Disabled by noPanel" > $OSAL_PATH_APACHE_CONF/sites-available/default
        echo "# Disabled by noPanel" > $OSAL_PATH_APACHE_CONF/sites-available/default-ssl
        echo -e "/home\npublic_html/cgi-bin" > /etc/apache2/suexec/www-data
    fi

    nplib_modules_set_installed 'apache' 'true'
    nplib_modules_set 'apache' 'serviceName' "$OSAL_SERVICE_APACHE"

    nplib_modules_set 'web' 'server' 'apache'
    nplib_modules_set 'web' 'logs' "/var/log/$OSAL_PKG_APACHE"

    nplib_command_echo " - Enabling and starting Apache service"
    osal_service_enable $OSAL_SERVICE_APACHE > /dev/null 2>&1
    osal_service_start $OSAL_SERVICE_APACHE > /dev/null 2>&1
        
    nplib_command_return 'ok' 'Apache module installed'
}
