#!/bin/bash

nopanel_module_apache_reload() {
    nplib_auto_elevate
    nplib_command_echo "= Reloading Apache web server"

    apachectl -k graceful
        
    nplib_command_output 'ok' 'Apache config reloaded'
}
