#!/bin/bash

nopanel_user_add() {
    if [[ "$param_help" ]]; then
        nopanel user help
        return
    fi

    if [[ ! "$param_user" ]]; then
        nplib_command_output 'error' 'Username not specified (--user)'
        return
    fi
    if [[ ! "$param_password" ]]; then
        nplib_command_output 'error' 'User password not specified (--password)'
        return
    fi

    nplib_require $NOPANEL_LIB/user.inc

    # Create user
    nplib_users_set "$param_user" 'name' "$param_user"

    # Set defaults
    [[ "$param_shell" ]] || param_shell='/bin/bash'

    # Call mod -> commit
    nopanel user mod

    nplib_command_output 'ok' 'User added'
}
