#!/bin/bash

nopanel_user_diff() {
    nplib_command_echo "= User diff"

    if [[ "$param_help" ]]; then
        nopanel user help
        return
    fi

    nplib_auto_elevate
    nplib_require $NOPANEL_LIB/user.inc
    nplib_require $NOPANEL_LIB/commit.inc

    local DELETED=$(nplib_commits_get_deleted $NOPANEL_ETC/users.json)
    local CHANGED=$(nplib_commits_get_changed $NOPANEL_ETC/users.json)

    nplib_command_output 'ok' 'User diff' "{deleted: \"$DELETED\", changed: \"$CHANGED\"}"
}
