#!/bin/bash

nopanel_user_help() {
    echo "Usage:"
    echo ""
    echo "  user add --user=USERNAME --password=PASSWORD --email=EMAIL [--shell=SHELL] [--fullname=FULL_NAME] [--force]"
    echo "  user mod --user=USERNAME [--password=PASSWORD] [--email=EMAIL] [--shell=SHELL] [--fullname=FULL_NAME]"
    echo "  user remove --user=USERNAME --force [--no-backup]"
}