#!/bin/bash

nopanel_user_help() {
    echo "Usage:"
    echo ""
    echo "  user add --username=USERNAME --password=PASSWORD --email=EMAIL [--shell=SHELL] [--contact=CONTACT_NAME] [--force]"
    echo "  user remove --username=USERNAME --force [--no-backup]"
}