#!/bin/bash

nopanel_user_list() {
    nplib_command_echo "= List users"

    if [[ "$param_help" ]]; then
        nopanel user help
        return
    fi

    nplib_require $NOPANEL_LIB/user.inc

    if [ "$param_output" = 'json' ]; then
        local userlist=$(nplib_users_list_json)
        nplib_command_output 'ok' 'User list' "$userlist"
    else
        local userlist=$(nplib_users_list)
        nplib_command_output 'ok' 'User list' "$userlist"
    fi

}
