#!/bin/bash

nopanel_user_list() {
    if [[ "$param_help" ]]; then
        nopanel user help
        return
    fi

    source $NOPANEL_LIB/user.inc

    if [[ "$param_output_json" ]]; then
        local userlist=$(nplib_user_get_json)
        nopanel_command_return 'ok' 'User list' "$userlist"
    else
        local userlist=$(nplib_user_get)
        nopanel_command_return 'ok' 'User list' "$userlist"
    fi

}
