#!/bin/bash

nopanel_user_mod() {
    if [[ "$param_help" ]]; then
        nopanel user help
        return
    fi

    if [[ ! "$param_user" ]]; then
        nplib_command_output 'error' 'Username not specified (--user)'
        return
    fi

    nplib_users_exists

    # anything not falsey is 'yes'
    [[ "$param_admin" ]] && param_admin='yes'
    
    [[ "$param_fullname" ]] &&nplib_users_set "$param_user" 'fullname' "$param_fullname"
    [[ "$param_email" ]] &&nplib_users_set "$param_user" 'email' "$param_email"
    [[ "$param_shell" ]] && nplib_users_set "$param_user" 'shell' "$param_shell"
    [[ "$param_admin" ]] &&nplib_users_set "$param_user" 'admin' "$param_admin"

    # Commit changes to system
    nopanel user commit
    
    # change password if specified
    if [[ "$param_password" ]]; then
        nplib_command_echo ' - Setting password'
        echo "$param_user:$param_password" | /usr/sbin/chpasswd
    fi

    nplib_command_output 'ok' 'User changed'
}
