#!/bin/bash

nopanel_user_mod() {
    nplib_command_echo "= Set user"

    if [[ "$param_help" ]]; then
        nopanel user help
        return
    fi

    if [[ ! "$param_user" ]]; then
        nplib_command_output 'error' 'Username not specified (--user)'
        return
    fi

    if [[ "$param_admin" ]] && ! nplib_is_bool "$param_admin"; then
        nplib_command_output 'error' 'Invalid value for --admin'
        return 1
    fi

    nplib_require $NOPANEL_LIB/user.inc

    if ! nplib_users_exists "$param_user"; then
        nplib_command_output 'error' 'User does not exist'
        return
    fi
    
    nplib_users_set "$param_user" 'delete' 'no'
    [[ "$param_fullname" ]] && nplib_users_set "$param_user" 'fullname' "$param_fullname"
    [[ "$param_email" ]] && nplib_users_set "$param_user" 'email' "$param_email"
    [[ "$param_shell" ]] && nplib_users_set "$param_user" 'shell' "$param_shell"
    [[ "$param_admin" ]] && nplib_users_set "$param_user" 'admin' $(nplib_bool_value $param_admin)
    [[ "$param_password" ]] && nplib_users_set "$param_user" 'password' "$param_password"
    
    if [[ "$param_commit" ]]; then
        nopanel user commit
    fi

    nplib_command_output 'ok' 'User saved'
}
