#!/bin/bash

nopanel_user_remove() {
    if [[ "$param_help" ]]; then
        nopanel user help
        return
    fi

    if [[ ! "$param_force" ]]; then
        nplib_command_return 'error' 'Refusing to remove user unless --force is used'
        return
    fi

    if [[ ! "$param_user" ]]; then
        nplib_command_return 'error' 'Username not specified (--user)'
        return
    fi

    local USER_JSON=$NOPANEL_ETC/users/${param_user}.json
    chattr -i "$NOPANEL_HOME/$param_user/conf" > /dev/null 2>&1
    if [[ ! "$param_no_backup" ]]; then
        nplib_config_backup "user-remove-$param_user" $NOPANEL_HOME/$param_user $USER_JSON
    fi
    /usr/sbin/userdel $param_user > /dev/null 2>&1
    nplib_safe_rm "$NOPANEL_HOME/$param_user" $USER_JSON

    osal_json_set "$NOPANEL_ETC/nopanel.json" "del(.users[] | select(.name == \"$param_user\"))"

    nplib_command_return 'ok' 'User removed'
}
