#!/bin/bash

nopanel_user_remove() {
    if [[ "$param_help" ]]; then
        nopanel user help
        return
    fi

    if [[ ! "$param_user" ]]; then
        nplib_command_output 'error' 'Username not specified (--user)'
        return
    fi

    if [[ ! "$param_force" ]]; then
        nplib_command_output 'error' 'Refusing to remove user unless --force is used'
        return
    fi

    nplib_require $NOPANEL_LIB/user.inc

    nplib_users_set "$param_user" 'delete' 'yes'

    nplib_command_output 'ok' 'User removed'

    if [[ "$param_commit" ]]; then
        nopanel user commit
    fi
}
