#!/bin/bash

nopanel_database_add() {
    if [[ "$param_help" ]]; then
        nopanel web help
        return
    fi


    if [[ ! "$param_user" ]]; then
        nopanel_command_return 'error' 'Username not specified (--user)'
        return
    fi
    if [[ ! "$param_db" ]]; then
        nopanel_command_return 'error' 'Database name not specified (--db)'
        return
    fi

    [[ "$param_dbuser" ]] || param_dbuser=$param_db
    local full_db_name="${param_user}_${param_db}"

    # Update noPanel DB
    nopanel_command_echo "Creating database $param_db for user $param_user..."

    nplib_databases_set "$full_db_name" 'name' "$param_db"
    nplib_databases_set "$full_db_name" 'user' "$param_user"
    nplib_databases_set "$full_db_name" 'type' 'mariadb'
    nplib_databases_set "$full_db_name" 'dbuser' "$param_dbuser"
    nplib_databases_set "$full_db_name" 'password' "$param_password"

    # Create database
    nopanel database rebuild

    nopanel_command_return 'ok' 'Database created'
}
