#!/bin/bash

nopanel_database_commit() {
    if [[ "$param_help" ]]; then
        nopanel db help
        return
    fi

    nplib_auto_elevate
    nplib_require $NOPANEL_LIB/user.inc
    nplib_require $NOPANEL_LIB/database.inc

    if [[ "$param_user" ]]; then
        nopanel_db_rebuild_user "$param_user"
    else
        # Rebuild all users
        for param_user in $(nplib_users_list); do
            nopanel_db_rebuild_user
        done
        unset param_user
    fi

    nplib_command_output 'ok' 'Domain configuration generated'
}


nopanel_db_rebuild_user() {
    nplib_command_echo " - Processing user $param_user..."
    if [[ "$param_db" ]]; then
        nopanel_db_rebuild_user_db
    else
        # Rebuild all domaind
        for param_db in $(nplib_databases_list "$param_user"); do
            nopanel_db_rebuild_user_db
        done
        unset param_db
    fi
}

nopanel_db_rebuild_user_db() {
    local full_db_name="${param_user}_${param_db}"
    local param_dbuser=$(nplib_databases_get "full_db_name" 'dbuser')
    local param_password=$(nplib_databases_get "full_db_name" 'password')

    nplib_command_echo "  - Setting up database $full_db_name..."

    nplib_require $NOPANEL_LIB/domain.inc
    
    nopanel_db_mysql_query "CREATE DATABASE IF NOT EXISTS \`$full_db_name\`"
    nopanel_db_mysql_query "GRANT ALL ON \`$full_db_name\`.* TO \`$param_dbuser\`@\`%\` IDENTIFIED BY '$param_password'"
    nopanel_db_mysql_query "GRANT ALL ON \`$full_db_name\`.* TO \`$param_dbuser\`@localhost IDENTIFIED BY '$param_password'"
}

nopanel_db_mysql_query() {
    local tmpfile=$(mktemp)
    echo "$1" > $tmpfile
    mysql < "$tmpfile"  2>/dev/null
    rm -f "$tmpfile"
}