#!/bin/bash

nopanel_database_diff() {
    nplib_command_echo "= Database diff"
    if [[ "$param_help" ]]; then
        nopanel web help
        return
    fi

    if [[ ! "$param_user" ]]; then
        nplib_command_output 'error' 'Username not specified (--user)'
        return
    fi

    nplib_auto_elevate
    nplib_require $NOPANEL_LIB/module.inc
    nplib_require $NOPANEL_LIB/user.inc
    nplib_require $NOPANEL_LIB/domain.inc
    nplib_require $NOPANEL_LIB/commit.inc

    local DELETED=$(nplib_commits_get_deleted $NOPANEL_HOME/$param_user/.nopanel/databases.json)
    local CHANGED=$(nplib_commits_get_changed $NOPANEL_HOME/$param_user/.nopanel/databases.json)
    
    nplib_command_output 'ok' 'Database diff' "{deleted: \"$DELETED\", changed: \"$CHANGED\"}"
}