#!/bin/bash

nopanel_database_list() {
    if [[ "$param_help" ]]; then
        nopanel web help
        return
    fi

    if [[ ! "$param_user" ]]; then
        nopanel_command_return 'error' 'Username not specified (--user)'
        return
    fi

    source $NOPANEL_LIB/database.inc

    if [[ "$param_output_json" ]]; then
        local dblist=$(nplib_database_get_json)
        nopanel_command_return 'ok' 'Database list' "$dblist"
    else
        local dblist=$(nplib_database_get)
        nopanel_command_return 'ok' 'Database list' "$dblist"
    fi

}
