#!/bin/bash

nopanel_database_list() {
    if [[ "$param_help" ]]; then
        nopanel web help
        return
    fi

    if [[ ! "$param_user" ]]; then
        nplib_command_return 'error' 'Username not specified (--user)'
        return
    fi

    nplib_require $NOPANEL_LIB/database.inc

    if [ "$param_output" = 'json' ]; then
        local dblist=$(nplib_databases_list_json)
        nplib_command_return 'ok' 'Database list' "$dblist"
    else
        local dblist=$(nplib_databases_list)
        nplib_command_return 'ok' 'Database list' "$dblist"
    fi

}
