#!/bin/bash

nopanel_database_mod() {
    nplib_command_echo "= Set database"

    if [[ "$param_help" ]]; then
        nopanel database help
        return
    fi

    if [[ ! "$param_user" ]]; then
        nplib_command_output 'error' 'Username not specified (--user)'
        return
    fi

    if [[ ! "$param_db" ]]; then
        nplib_command_output 'error' 'Database name not specified (--db)'
        return
    fi

    nplib_require $NOPANEL_LIB/database.inc

    local DB_FULLNAME="${param_user}_${param_db}"

    if ! nplib_databases_exists "$DB_FULLNAME"; then
        nplib_command_output 'error' 'Database does not exist'
        return
    fi

    # Update noPanel DB
    nplib_databases_set "$DB_FULLNAME" 'delete' 'no'
    [[ "$param_password" ]] && nplib_databases_set "$DB_FULLNAME" 'password' "$param_password"

    if [[ "$param_commit" ]]; then
        nopanel database commit
    fi

    nplib_command_output 'ok' 'Database saved'
}
