#!/bin/bash

nopanel_database_mod() {
    if [[ "$param_help" ]]; then
        nopanel database help
        return
    fi

    if [[ ! "$param_user" ]]; then
        nplib_command_output 'error' 'Username not specified (--user)'
        return
    fi

    if [[ ! "$param_db" ]]; then
        nplib_command_output 'error' 'Database name not specified (--db)'
        return
    fi

    nplib_require $NOPANEL_LIB/database.inc

    local full_db_name="${param_user}_${param_db}"

    if ! nplib_databases_exists "$full_db_name"; then
        nplib_command_output 'error' 'Database does not exist'
        return
    fi

    # Update noPanel DB
    nplib_command_echo "Creating database $param_db for user $param_user..."

    nplib_databases_set "$full_db_name" 'password' "$param_password"

    if [[ "$param_commit" ]]; then
        nopanel database commit
    fi

    nplib_command_output 'ok' 'Database saved'
}
