#!/bin/bash

nopanel_database_remove() {
    nplib_command_echo "= Remove database"

    if [[ "$param_help" ]]; then
        nopanel user help
        return
    fi

    if [[ ! "$param_user" ]]; then
        nplib_command_output 'error' 'Username not specified (--user)'
        return
    fi

    if [[ ! "$param_db" ]]; then
        nplib_command_output 'error' 'Database name not specified (--db)'
        return
    fi

    if [[ ! "$param_force" ]]; then
        nplib_command_output 'error' 'Refusing to remove user unless --force is used'
        return
    fi

    nplib_require $NOPANEL_LIB/database.inc

    local DB_FULLNAME="${param_user}_${param_db}"

    if ! nplib_databases_exists "$DB_FULLNAME"; then
        nplib_command_output 'error' 'Database does not exist'
        return
    fi

    nplib_require $NOPANEL_LIB/database.inc

    nplib_databases_set "$DB_FULLNAME" 'delete' 'yes'

    if [[ "$param_commit" ]]; then
        nopanel database commit
    fi

    nplib_command_output 'ok' 'Database removed'
}
