#!/bin/bash

nopanel_module_mariadb_wipe() {
    nplib_elevate
    if [[ ! "$param_force" ]]; then
        nplib_command_output 'error' 'Refusing to wipe MariaDB unless --force is used'
        return
    fi

    nplib_command_echo "Wiping noPanel MariaDB module..."

    osal_service_stop $OSAL_SERVICE_MARIADB > /dev/null 2>&1
    nplib_config_backup 'mariadb-install' $OSAL_PATH_MARIADB_CONF $OSAL_DIR_MARIADB_CONF_D $OSAL_PATH_MARIADB_DATA \
        /etc/apt/sources.list.d/mariadb.list /etc/yum.repos.d/mariadb.repo ~/.my.cnf

    osal_package_remove ${OSAL_PKG_MARIADB}-server ${OSAL_PKG_MARIADB}-client ${OSAL_PKG_MARIADB}-common > /dev/null 2>&1

    nplib_safe_rm $OSAL_PATH_MARIADB_CONF $OSAL_DIR_MARIADB_CONF_D $OSAL_PATH_MARIADB_DATA \
        /etc/apt/sources.list.d/mariadb.list /etc/yum.repos.d/mariadb.repo ~/.my.cnf

    osal_json_set "$NOPANEL_ETC/modules.json" ".mariadb.installed = \"false\" | .mariadb.serviceName = \"\"" 
    osal_json_set "$NOPANEL_ETC/modules.json" ".mariadb.host = \"localhost\" | .mariadb.port = \"\" | .mariadb.user = \"\" | .mariadb.password = \"\""
        
    nplib_command_output 'ok' 'MariaDB module removed'
}
